class InvalidToken(Exception): ...

class Fernet:
    def __init__(self, key: bytes) -> None: ...
    @classmethod
    def generate_key(cls) -> bytes: ...
    def encrypt(self, data: bytes) -> bytes: ...
    def decrypt(self, token: bytes | str, ttl: int | None = ...) -> bytes: ...
