services:
  okonebo:
    image: okonebo:latest
    build: .
    container_name: okonebo
    ports:
      - "8888:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./secure_settings.db:/app/secure_settings.db
      - ./cache.db:/app/cache.db
